### ISSUE TITLE
How to make notes contents as list without sub-directory

### ISSUE THREAD

**Issue by yanboyang713** [hugo-toha/hugo-toha.github.io#239]
Hello All,

I found notes contents must within a sub-directory. how could I make notes contents as list without directory? example below

```
root-content-notes
                   -_index.md
                   -aaa.md
                   -bbb.md
                   -ccc.md
```

Current default:
```
root-content-notes
                   - _index.md
                   - a-directory
                                     - _index.md
                                     - aaa.md
                   - b-directory
                                     - _index.md
                                     - bbb.md
```

Thanks

**Comment by hossainemruz** [comment]
Sorry, I was not responsive for few month due to some personal issue. You should be able to write notes without sub-directory. There might be some changes necessary in the front-matter.

**Comment by yanboyang713** [comment]
Hello @hossainemruz ,

Thanks for your reply.

Even **content/notes** DIR only has one .md file. my [web](https://www.yanboyang.com/notes/) could not works.

Could you give me an example of the correct front matter?

```
yanboyang713@Meta-Scientific-Linux ~/personalblog/content/notes (git)-[main] % ls
one.md
yanboyang713@Meta-Scientific-Linux ~/personalblog/content/notes (git)-[main] % cat one.md
+++
title = "emacs first"
date = 2021-12-21T16:16:00-05:00
categories = ["Editor", "emacs"]
draft = false
+++

1st
```

**Comment by hossainemruz** [comment]
Please try following front-matter.
```yaml
---
title: "emacs first"
date: 2021-12-21T16:16:00-05:00
categories: ["Editor", "emacs"]
draft: false
menu:
  notes:
    name: "Variables"
    identifier: "notes-bash-variables"
    weight: 1
---
```
