### ISSUE TITLE
Customize web logo in dark and bright mode

### ISSUE THREAD

**Issue by jackwu925** [hugo-toha/hugo-toha.github.io#373]
Hello, is there any possibility to customize the website logo on the upper-left side in dark and bright mode respectively?

I found the code in <hugo.yaml> file, but it seems that the logo here works for both modes at the same time.

  logo:
    main: images/inverted-logo.svg
    inverted: images/inverted-logo.svg
    favicon: images/inverted-logo.svg

**Comment by hossainemruz** [comment]
Yes. You can use `logo.dark` for dark mode logo. I thought it was already shown in the `hugo.yaml` of this example site.

```yaml
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png
    dark: /images/site/your-dark-logo.png
```
